apiVersion: v1
kind: Service
metadata:
  name: workload-api
  labels:
    app.kubernetes.io/name: workload-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: workload-api