SATURATION_RPS = int(25*.8)  # 80% of the threshold RPS
SPAWN_RATE = SATURATION_RPS  # VUs per second
CYCLE_TIME = 15 * 60

NUMBER_OF_CYCLES = 8
EXPERIMENT_DURATION = NUMBER_OF_CYCLES * CYCLE_TIME

LOAD_LEVELS = (
    0.5 * SATURATION_RPS,
    1.5 * SATURATION_RPS,
    2.5 * SATURATION_RPS,
    3.5 * SATURATION_RPS,
)

MIN_RPS = LOAD_LEVELS[0]
MAX_RPS = LOAD_LEVELS[-1]