keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 15
  prometheus:
    serverAddress: http://prometheus-operated.monitoring.svc:9090
    threshold: "40"
    query: |
      sum(rate(traefik_service_requests_total{exported_service=~".*workload-api.*"}[1m]))